### ISSUE TITLE
use-of-uninitialized-value from al_load_config_file

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#1087]
```
Uninitialized bytes in __interceptor_memcmp at offset 0 inside [0x701000000127, 1)
==800985==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fda0304aa97 in _al_biseq /home/dos/git/allegro5/build/../src/misc/bstrlib.c:805:10
    #1 0x7fda0304812f in al_ustr_has_suffix /home/dos/git/allegro5/build/../src/utf8.c:971:11
    #2 0x7fda03048193 in al_ustr_has_suffix_cstr /home/dos/git/allegro5/build/../src/utf8.c:982:11
    #3 0x7fda02fade02 in readline /home/dos/git/allegro5/build/../src/config.c:301:11
    #4 0x7fda02fadf93 in al_load_config_file_f /home/dos/git/allegro5/build/../src/config.c:350:12
    #5 0x7fda02fade85 in al_load_config_file /home/dos/git/allegro5/build/../src/config.c:318:13
    #6 0x7fda02fdf4b7 in read_allegro_cfg /home/dos/git/allegro5/build/../src/system.c:134:11
    #7 0x7fda02fdf786 in al_install_system /home/dos/git/allegro5/build/../src/system.c:241:4
    #8 0x7fda031f2fd1 in libsuperderpy_init /home/dos/git/odglos/build-qtcreator/Clang-Debug/../../libsuperderpy/src/libsuperderpy.c:69:7
    #9 0x55cc379cc2f9 in engine_setup /home/dos/git/odglos/build-qtcreator/Clang-Debug/../../libsuperderpy/test/tests.c:22:11
    #10 0x55cc379cf1f6 in timeline_setup /home/dos/git/odglos/build-qtcreator/Clang-Debug/../../libsuperderpy/test/timeline.c:130:9
    #11 0x7fda03264582  (/usr/lib/libcmocka.so.0+0x6582)
    #12 0x7fda03264915 in _cmocka_run_group_tests (/usr/lib/libcmocka.so.0+0x6915)
    #13 0x55cc379cc5ab in test_timeline /home/dos/git/odglos/build-qtcreator/Clang-Debug/../../libsuperderpy/test/timeline.c:436:9
    #14 0x55cc379cc493 in main /home/dos/git/odglos/build-qtcreator/Clang-Debug/../../libsuperderpy/test/tests.c:34:9
    #15 0x7fda02c36ee2 in __libc_start_main (/usr/lib/libc.so.6+0x26ee2)
    #16 0x55cc379501dd in _start (/home/dos/git/odglos/build-qtcreator/Clang-Debug/libsuperderpy/test/engine-tests+0x211dd)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/dos/git/allegro5/build/../src/misc/bstrlib.c:805:10 in _al_biseq
Exiting
```

**Comment by dos1** [comment]
ah, silly me, allegro wasn't instrumented there...
