### ISSUE TITLE
Double free at exit with ALLEGRO_PROGRAMMABLE_PIPELINE on Linux

### ISSUE THREAD

**Issue by frank256** [liballeg/allegro5#1152]
Running the shader examples on Linux (Ubuntu 18.04, Intel graphics, Allegro 5.2.6), I reliably get a segfault on program exit. It only occurs if the display has been created with ALLEGRO_PROGRAMMABLE_PIPELINE.
After investigating with valgrind, the reason appears to be a double free (see below).
If I add a manual call to `al_uninstall_system` before exit, the problem disappears.

```
==30685== Invalid free() / delete / delete[] / realloc()
==30685==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30685==    by 0xBF5C284: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0xBD5FECD: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0xBC1877E: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0xBCB77F2: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0x9C3281E: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
==30685==    by 0x9C1BB69: ??? (in /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0)
==30685==    by 0x4ED8B7D: xdpy_destroy_display_hook_default (xdisplay.c:699)
==30685==    by 0x4ED868F: xdpy_destroy_display (xdisplay.c:767)
==30685==    by 0x4EE2881: xglx_shutdown_system (xsystem.c:272)
==30685==    by 0x4E9E644: shutdown_system_driver (system.c:81)
==30685==    by 0x4E9836C: _al_run_exit_funcs (exitfunc.c:92)
==30685==  Address 0x11781180 is 0 bytes inside a block of size 48 free'd
==30685==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30685==    by 0x538E0F0: __run_exit_handlers (exit.c:108)
==30685==    by 0x538E1E9: exit (exit.c:139)
==30685==    by 0x536CB9D: (below main) (libc-start.c:344)
==30685==  Block was alloc'd at
==30685==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==30685==    by 0xC01FB1C: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0xBF45255: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0xBE22CC6: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==30685==    by 0x4F00813: glsl_attach_shader_source (ogl_shader.c:128)
==30685==    by 0x4E9E448: _al_create_default_shader (shader.c:481)
==30685==    by 0x4E94812: al_create_display (display.c:104)
==30685==    by 0x1094EC: main (main.cpp:76)
```

**Comment by rmbeer** [comment]
You can build a testcase with the error?

**Comment by frank256** [comment]
The official examples with shaders would lead to the error, e.g. ex_shader, ex_shader_multitex, ex_shader_target.

**Comment by SiegeLord** [comment]
I can reproduce this w/ AMD drivers too, but attempts at fixing this have not yet suceeded. I can get a different backtrace if I merely create the display and exit:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c3e859 in __GI_abort () at abort.c:79
#2  0x00007fffed7f9c28 in  () at /lib/x86_64-linux-gnu/libLLVM-11.so.1
#3  0x00007fffedd1ec01 in  () at /lib/x86_64-linux-gnu/libLLVM-11.so.1
#4  0x00007fffedd1e69c in llvm::TargetPassConfig::addMachinePasses() () at /lib/x86_64-linux-gnu/libLLVM-11.so.1
#5  0x00007fffedb25552 in llvm::LLVMTargetMachine::addPassesToEmitFile(llvm::legacy::PassManagerBase&, llvm::raw_pwrite_stream&, llvm::raw_pwrite_stream*, llvm::CodeGenFileType, bool, llvm::MachineModuleInfoWrapperPass*) () at /lib/x86_64-linux-gnu/libLLVM-11.so.1
#6  0x00007ffff2523a17 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#7  0x00007ffff25b5190 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#8  0x00007ffff2585012 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#9  0x00007ffff25863da in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#10 0x00007ffff1f1dc40 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#11 0x00007ffff254f9bc in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#12 0x00007ffff22a2373 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#13 0x00007ffff22a6f41 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#14 0x00007ffff22a8618 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#15 0x00007ffff2d2f405 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#16 0x00007ffff2cace10 in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#17 0x00007ffff2d6b20b in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#18 0x00007ffff2da51ed in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#19 0x00007ffff281ec8e in  () at /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#20 0x00007ffff38d5e6d in  () at /lib/x86_64-linux-gnu/libGLX_mesa.so.0
#21 0x00007ffff68c82a3 in  () at /lib/x86_64-linux-gnu/libGLX.so.0
#22 0x00007ffff68c9a9f in  () at /lib/x86_64-linux-gnu/libGLX.so.0
#23 0x00007ffff7f2c3a7 in xdpy_unset_current_display (d=0x5555555db3e0) at /home/siege/src/A5/git/src/x/xdisplay.c:825
#24 0x00007ffff7eb6790 in al_set_target_bitmap (bitmap=0x0) at /home/siege/src/A5/git/src/tls.c:461
#25 0x00007ffff7e9c956 in al_destroy_display (display=0x5555555db3e0) at /home/siege/src/A5/git/src/display.c:155
#26 0x00007ffff7f35565 in xglx_shutdown_system () at /home/siege/src/A5/git/src/x/xsystem.c:272
#27 0x00007ffff7eb2f4b in shutdown_system_driver () at /home/siege/src/A5/git/src/system.c:81
#28 0x00007ffff7ea396b in _al_run_exit_funcs () at /home/siege/src/A5/git/src/exitfunc.c:93
#29 0x00007ffff7eb34a1 in al_uninstall_system () at /home/siege/src/A5/git/src/system.c:322
#30 0x00007ffff7c62a27 in __run_exit_handlers
    (status=0, listp=0x7ffff7e04718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#31 0x00007ffff7c62be0 in __GI_exit (status=<optimized out>) at exit.c:139
#32 0x00007ffff7c400ba in __libc_start_main (main=
--Type <RET> for more, q to quit, c to continue without paging--
    0x55555555687c <main(int, char**)>, argc=1, argv=0x7fffffffdf18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf08) at ../csu/libc-start.c:342
#33 0x000055555555638e in _start ()
```

In addition, it prints this:

```
LLVM ERROR: "@/����hUUU�[" pass is not registered.
```

Something is quite wrong, as this did not use to happen.

**Comment by SiegeLord** [comment]
Nevermind, that second backtrace is unrelated. Still no luck with the original error, it appears enough to just compile the shader to get the crash to happen. I have standalone code to create a GLX context + shaders that doesn't crash, so dissecting that is the next step.
