### ISSUE TITLE
Alignment requirement for ALLEGRO_EVENT_SOURCE too lax

### ISSUE THREAD

**Issue by tehsausage** [liballeg/allegro5#1271]
I'm not sure how I should fix this because it would be a breaking ABI change.

The alignment of ALLEGRO_EVENT_SOURCE as defined here is only 4 bytes (on non-Windows platforms): 

```c
struct ALLEGRO_EVENT_SOURCE
{
   int __pad[32];
};
```

But it later gets converted to this type:

```c
struct ALLEGRO_EVENT_SOURCE_REAL
{
   _AL_MUTEX mutex;
   _AL_VECTOR queues;
   intptr_t data;
};
```

And used in a context which requires an alignment of 8 bytes, which triggers ubsan:

```
[...]/src/evtsrc.c:42:4: runtime error: member access within misaligned address 0x612000001bb4 for type 'struct ALLEGRO_EVENT_SOURCE_REAL', which requires 8 byte alignment
0x612000001bb4: note: pointer points here
  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^ 
    #0 0x7fd1ca7ba9a4 in _al_event_source_init [...]src/evtsrc.c:42
    #1 0x7fd1ca7bb238 in al_init_user_event_source [...]/src/evtsrc.c:199
    #2 0x7fd1cb6677dd in al_open_native_text_log [...]/addons/native_dialog/textlog.c:56
    #3 0x55c5c21086ee in open_log [...]/examples/common.c:52
    #4 0x55c5c2108ca9 in main [...]/examples/ex_acodec.c:42
    #5 0x7fd1c95017ec in __libc_start_main ../csu/libc-start.c:332
    #6 0x55c5c21083f9 in _start ([...]/a5-ubsan-native-Debug/examples/ex_acodec+0x33f9)
```

I would propose changing the definition of ALLEGRO_EVENT_SOURCE as follows:

```c
struct ALLEGRO_EVENT_SOURCE
{
   long __pad[16];
};
```

However, this results in the size of ALLEGRO_EVENT_SOURCE shrinking from 256 bytes to 128 bytes on 64-bit Windows.

Another solution would be to use __attribute((aligned)) to force the alignment of ALLEGRO_EVENT_SOURCE to be larger where possible, or to use #ifdef's to preserve the current struct size on Windows.

Maybe add the alignment attribute for the rest of 5.2 and then switch it to long[16] in 5.3?

Technically an increase in alignment requirement is an ABI break, however the code is already being generated assuming the larger alignment, so not really.

**Comment by tehsausage** [comment]
P.S. ALLEGRO_EVENT_SOURCE is used in user-code to provide storage for user-event sources.

**Comment by SeanTolstoyevski** [comment]
This seems like good research and a good suggestion.

Why is the core team not responding?

**Comment by allefant** [comment]
> This seems like good research and a good suggestion.
> 
> Why is the core team not responding?

tehsausage is core team and likely nobody else knows more about pointer alignment issues - once there's a PR it will get applied.
