### ISSUE TITLE
X errors on master

### ISSUE THREAD

**Issue by rcorre** [liballeg/allegro5#606]
On an ArchLinux machine with an nvidia card, I see this whenever I close an allegro program:

```
X Error of failed request:  181
  Major opcode of failed request:  154 ()
  Minor opcode of failed request:  32
  Serial number of failed request:  213
  Current serial number in output stream:  213
```

I managed to get a more helpful message once:

```
The program 'ex_audio_simple' received an X Window System error.
This probably reflects a bug in the program.
The error was '181'.
  (Details: serial 88 error_code 181 request_code 154 minor_code 32)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I haven't figured out exactly where I'm supposed to say `--sync` yet...

I have `libX11 1.6.3`.
It seems fine on an ArchLinux laptop with intel graphics but an otherwise similar setup.

A stack trace that may or may not be helful, from breaking on `_XError`:

```
Thread 1 "ex_display_opti" hit Breakpoint 1, 0x00007ffff65fa760 in _XError () from /usr/lib/libX11.so.6
(gdb) bt
#0  0x00007ffff65fa760 in _XError () from /usr/lib/libX11.so.6
#1  0x00007ffff1a1fa52 in ?? () from /usr/lib/libGLX.so.0
#2  0x00007ffff1a23234 in ?? () from /usr/lib/libGLX.so.0
#3  0x00007ffff1a233a9 in glXDestroyWindow () from /usr/lib/libGLX.so.0
#4  0x00007ffff73326f7 in xdpy_destroy_display_hook_default (d=0x666ee0, is_last=true) at /home/rcorre/projects/contrib/allegro/src/x/xd
#5  0x00007ffff73329b3 in xdpy_destroy_display (d=0x666ee0) at /home/rcorre/projects/contrib/allegro/src/x/xdisplay.c:706
#6  0x00007ffff72a4939 in al_destroy_display (display=0x666ee0) at /home/rcorre/projects/contrib/allegro/src/display.c:169
#7  0x00007ffff733dc77 in xglx_shutdown_system () at /home/rcorre/projects/contrib/allegro/src/x/xsystem.c:108
#8  0x00007ffff72b9f50 in shutdown_system_driver () at /home/rcorre/projects/contrib/allegro/src/system.c:81
#9  0x00007ffff72ab4ea in _al_run_exit_funcs () at /home/rcorre/projects/contrib/allegro/src/exitfunc.c:92
#10 0x00007ffff72ba402 in al_uninstall_system () at /home/rcorre/projects/contrib/allegro/src/system.c:305
#11 0x00007ffff2c56c38 in __run_exit_handlers () from /usr/lib/libc.so.6
#12 0x00007ffff2c56c85 in exit () from /usr/lib/libc.so.6
#13 0x00007ffff2c41717 in __libc_start_main () from /usr/lib/libc.so.6
#14 0x0000000000401dc9 in _start ()
(gdb)
```

**Comment by rcorre** [comment]
Duplicate
